### ISSUE TITLE
数据库已经有用户规则了，但是验证通过不了

### ISSUE THREAD

**Issue by Tinywan** [php-casbin/think-casbin#12]
![image](https://user-images.githubusercontent.com/14959876/75979407-674bd480-5f1b-11ea-9b5f-c50d54b5d37e.png)

接受参数
```
$result = Casbin::enforce($uid, $url, $action); // 返回false

权限认证]：uid=28 url=/api/v1/user/information action=GET
```

**Comment by leeqvip** [comment]
你的model.conf 发下

**Comment by Tinywan** [comment]
@techoner 
```
[request_definition]
r = sub, obj, act
# sub, obj, act 表示经典三元组: 访问实体 (Subject)，访问资源 (Object) 和访问方法 (Action)

[policy_definition]
p = sub, obj, act

# RBAC角色继承关系的定义
[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
#m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act

# RBAC + RESTful 权限控制
m = g(r.sub, p.sub) && keyMatch2(r.obj, p.obj) && regexMatch(r.act, p.act)
```

**Comment by leeqvip** [comment]
@Tinywan  按你的配置试了下正常的，你看下数据库连接信息是否配对了？
```
dump(Casbin::getPolicy());
```
看下能否拿到所有policy

**Comment by Tinywan** [comment]
@techoner 你是怎么验证的，我这边就是不行，我就是参考这个 https://tech1024.com/original/3019

**Comment by Tinywan** [comment]
我就写了个中间件
```
public function check(){
		$url = $this->request->url();
		$action = $this->request->method();
		$uid = Token::getCurrentUID();
		try {
			$result = Casbin::enforce($uid, $url, $action); // 返回false
                         // uid=28 url=/api/v1/user/information action=GET
		} catch (CasbinException $exception) {
			$result = false;
		}
		if (!$result) return false;
		return true;
}
```

**Comment by leeqvip** [comment]
@Tinywan 
![image](https://user-images.githubusercontent.com/35752209/76072536-1bf4fd00-5fd3-11ea-992d-eb74bae31a1e.png)

```php
dump(Casbin::getPolicy());
$res = Casbin::enforce('28', '/api/v1/user/information', 'GET');
var_dump($res);
```
输出：
```
array(1) {
  [0] => array(3) {
    [0] => string(2) "28"
    [1] => string(24) "/api/v1/user/information"
    [2] => string(3) "GET"
  }
}
bool(true)
```

**Comment by Tinywan** [comment]
@techoner 我这边获取到的是空的

### 数据库：
![image](https://user-images.githubusercontent.com/14959876/76073818-36c87100-5fd5-11ea-91f8-18b804076c85.png)

### 方法：
use CasbinAdapter\Think\Facades\Casbin;
![image](https://user-images.githubusercontent.com/14959876/76073699-fe289780-5fd4-11ea-9bbc-6f86fedd11f0.png)

### 输出结果：

![image](https://user-images.githubusercontent.com/14959876/76073908-5bbce400-5fd5-11ea-9d6b-7dce9f7b37a5.png)

**Comment by leeqvip** [comment]
数据库连接信息配置对了吗 估计你的数据库没连上，或者表名不对

**Comment by Tinywan** [comment]
1、网站都在跑，数据怎么可能没连击上，http://wiot.frp.tinywan.top/index/test/demo
代码
```
class Test extends Controller
{
    /**
     * @desc: 测试
     */
    public function demo()
    {
        dump(Casbin::getPolicy());
        $res = Casbin::enforce('28', '/api/v1/user/information', 'GET');
        dump($res);
        dump('--------------以下是数据库------');
        $rule = CasbinRuleModel::find(10);
        halt($rule);
    }
```
2、打印信息
![image](https://user-images.githubusercontent.com/14959876/76081420-076d3080-5fe4-11ea-8127-78f52cc7f08a.png)

3、我TP5版本是 `VERSION = '5.1.39 LTS';`

**Comment by Tinywan** [comment]
@techoner 方便加个QQ  看一下吗?

**Comment by Tinywan** [comment]
使用最新版本：`v1.0.3`
