### ISSUE TITLE
有使用文档吗

### ISSUE THREAD

**Issue by xzusoft** [php-casbin/think-casbin#3]
有使用文档吗

**Comment by hsluoyz** [comment]
@leubao please use English.

**Comment by xzusoft** [comment]
Are there more detailed documents? The existing documents are vague and not suitable for entry

**Comment by hsluoyz** [comment]
@techoner

**Comment by leeqvip** [comment]
Think-casbin：
1、实现think-orm的adapter
2、实现Casbin的门面think\Facade调用
3、model、adapter可配置化

使用门面拿到实例后，还是casbin的用法，参考：
php-casbin仓库：https://github.com/php-casbin/php-casbin
官方网站：https://casbin.org/

**Comment by xzusoft** [comment]
谢谢
