### ISSUE TITLE
可否更新一个6.0版本的？

### ISSUE THREAD

**Issue by Tokimekis** [php-casbin/think-casbin#4]

**Comment by hsluoyz** [comment]
@techoner

**Comment by leeqvip** [comment]
@Tokimekis  有这个计划

**Comment by hsluoyz** [comment]
Hi @Tokimekis , please use the ThinkPHP 6.0 middleware: https://github.com/php-casbin/think-authz

**Comment by Tokimekis** [comment]
@hsluoyz thx!
