### ISSUE TITLE
从数据库取策略的时候报错

### ISSUE THREAD

**Issue by rebootdd** [php-casbin/think-casbin#5]
![image](https://user-images.githubusercontent.com/27179034/63919191-d7f7cd00-ca70-11e9-934b-0c4a598000ac.png)
![image](https://user-images.githubusercontent.com/27179034/63919317-19887800-ca71-11e9-9a85-c9ae323b82f3.png)
![image](https://user-images.githubusercontent.com/27179034/63919365-31f89280-ca71-11e9-94b1-f9846881376d.png)
然后就一致报错，是不是可以把那个适配器改下

**Comment by leeqvip** [comment]
@rebootdd 升级到 ` v1.0.1` .

**Comment by rebootdd** [comment]
![image](https://user-images.githubusercontent.com/27179034/63949439-fb406d80-caac-11e9-82e6-b74eb6bd4760.png)
我用composer update报错了

**Comment by leeqvip** [comment]
这样写
```
"casbin/think-adapter": "^1.0"
```
或者
```
"casbin/think-adapter": "1.0.*"
```

**Comment by rebootdd** [comment]
谢谢了，问题解决了

**Comment by hongjinlin** [comment]
又报同样的错误
thinkphp 版本 v5.1.38 LTS

"casbin/think-adapter": "^1.0" 和 "casbin/think-adapter": "1.0.*"  都无法升级到 1.0.1

**Comment by rebootdd** [comment]
我没有在thinPHP5.1项目中下载think-adapter包，在空文件夹下composer后，再将包放到thinkphp项目中的，在thinkphp5.1中下载think-adapter包报错不知道如何解决 @ @hongjinlin

**Comment by hongjinlin** [comment]
> 我没有在thinPHP5.1项目中下载think-adapter包，在空文件夹下composer后，再将包放到thinkphp项目中的，在thinkphp5.1中下载think-adapter包报错不知道如何解决 @ @hongjinlin

好的，谢谢， 下回再试，我换了个库

**Comment by leeqvip** [comment]
可以贴一下composer.json及其报错

**Comment by hongjinlin** [comment]
> 可以贴一下composer.json及其报错

composer.json 里 "casbin/think-adapter": "^1.0" 和 "casbin/think-adapter": "1.0.*"，这两句都有试过，都不行，看了composer.lock, 引的都是 "version": "v1.0.0"，如果强制改成"casbin/think-adapter": "1.0.1"，就会报这个错误 https://github.com/php-casbin/think-casbin/issues/5#issuecomment-526214198

完整composer.json

"require": {
    "php": ">=5.6.0",
    "topthink/framework": "5.1.*",
    "php-amqplib/php-amqplib": "^2.10",
    "nesbot/carbon": "^2.23",
    "phpoffice/phpspreadsheet": "^1.9",
    "casbin/think-adapter": "^1.0",
    "owasp/phprbac": "2.0.*@dev"
  },

![image](https://user-images.githubusercontent.com/11484312/64147075-ca1bc080-ce51-11e9-946c-33c72e6cdb41.png)
github，会把"*"号过滤掉？

**Comment by leeqvip** [comment]
按你这个执行 `composer install` 是没有问题的。
可以尝试删除 `composer.lock`文件再 `composer install`
也可能是你使用的镜像同步太慢，可以使用阿里镜像
```
composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/
```

**Comment by hongjinlin** [comment]
> 按你这个执行 `composer install` 是没有问题的。
> 可以尝试删除 `composer.lock`文件再 `composer install`
> 也可能是你使用的镜像同步太慢，可以使用阿里镜像
> 
> ```
> composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/
> ```

好的，谢谢，阿里的镜像之前也试过了，问题依旧，可能其他因素导致的吧〜
