### ISSUE TITLE
thinkphp5.1下载不了think-adapter

### ISSUE THREAD

**Issue by rebootdd** [php-casbin/think-casbin#7]
![微信截图_20190909114712](https://user-images.githubusercontent.com/27179034/64502264-a2b47000-d2f7-11e9-8d4c-dba7829c0882.png)
我发现这个问题是因为tp5.1项目就是包topthink/think,而think-adapter依赖着topthink/think,相互依赖所以下载不了，如果依赖topthink/framework核心库，应该就能下载了，是不是？

**Comment by leeqvip** [comment]
@rebootdd 已经解决了，发布了v1.0.2，更新试下。

**Comment by rebootdd** [comment]
谢谢了，可以了
